# Generated by Django 3.2 on 2021-05-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('video_upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadVideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='')),
                ('thumbnail_file', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=64)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
