# Generated by Django 3.2 on 2021-05-13 02:52

import django.utils.timezone
from django.db import migrations, models

import video_upload.models


class Migration(migrations.Migration):
    dependencies = [
        ('video_upload', '0002_auto_20210505_2153'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.RenameField(
            model_name='uploadvideomodel',
            old_name='upload_date',
            new_name='uploadDate',
        ),
        migrations.RemoveField(
            model_name='uploadvideomodel',
            name='thumbnail_file',
        ),
        migrations.RemoveField(
            model_name='uploadvideomodel',
            name='video_file',
        ),
        migrations.AddField(
            model_name='uploadvideomodel',
            name='thumbnailFile',
            field=models.ImageField(default='16c5c4eb-612d-47d5-8512-18934eb8e38e.jpg',
                                    upload_to=video_upload.models.name_generator),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadvideomodel',
            name='videoFile',
            field=models.FileField(default=django.utils.timezone.now, upload_to=video_upload.models.name_generator),
            preserve_default=False,
        ),
    ]
