apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: vsr-cluster
  region: eu-central-1

nodeGroups:
  - name: ng-1
    instanceType: m5.xlarge
    desiredCapacity: 2
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        certManager: true
        appMesh: true
        appMeshPreview: true
        albIngress: true
        xRay: true
        cloudWatch: true
    ssh:
      publicKeyPath: ~/Desktop/public-key-pair.pem
