apiVersion: apps/v1
kind: Deployment
metadata:
  name: vsr-app
  labels:
    app: vsr-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vsr-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: vsr-app
    spec:
      containers:
        - image: 403364721735.dkr.ecr.eu-central-1.amazonaws.com/vsr-repo:c919dbfd0e67d8910e7e6bc6a0288c59342e39bc
          imagePullPolicy: Always
          name: vsr-app
          envFrom:
          - secretRef:
              name: vsr-secret
          - configMapRef:
              name: vsr-config
          ports:
            - containerPort: 8000
              protocol: TCP
              name: gunicorn