# Generated by Django 3.2 on 2021-04-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0002_alter_video_upload_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="audio_url",
            field=models.URLField(default="www.examples.com/audio.aac"),
            preserve_default=False,
        ),
    ]
