# Generated by Django 3.2 on 2021-05-13 02:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('video', '0005_auto_20210428_0413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='audio_key_s3',
            new_name='audioKeyS3',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='thumbnail_key_s3',
            new_name='thumbnailKeyS3',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='upload_date',
            new_name='uploadDate',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='video_key_s3',
            new_name='videoKeyS3',
        ),
    ]
