# Generated by Django 3.2 on 2021-04-28 04:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('video', '0004_auto_20210428_0220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='audio_url',
            new_name='audio_key_s3',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='thumbnail_url',
            new_name='thumbnail_key_s3',
        ),
    ]
